# Generated by Django 3.2 on 2023-08-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20230810_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(default=1, upload_to='country_images/'),
            preserve_default=False,
        ),
    ]
