# Generated by Django 3.2 on 2023-08-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_article_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentlyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('reader_name', models.CharField(max_length=100)),
            ],
        ),
    ]
