# Generated by Django 3.2 on 2023-08-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_currentlyreading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlyreading',
            name='book_title',
        ),
        migrations.RemoveField(
            model_name='currentlyreading',
            name='reader_name',
        ),
        migrations.AddField(
            model_name='currentlyreading',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='News.article'),
            preserve_default=False,
        ),
    ]
