# Generated by Django 3.2 on 2023-08-11 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_auto_20230811_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.article')),
            ],
        ),
        migrations.DeleteModel(
            name='CurrentlyReading',
        ),
    ]
