# Generated by Django 3.2 on 2023-08-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_auto_20230811_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
