# Generated by Django 3.2 on 2023-08-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='articles', verbose_name='Фото'),
        ),
    ]
